### ISSUE TITLE
Could you provide an osx-arm64 or noarch conda package?

### ISSUE THREAD

**Issue by FriederikeBrezing** [conda-forge/pyannote.database-feedstock#11]
### Comment:

On conda-forge, there are only conda packages for pyannote.database for osx-64, linux-64 and win-64 but not for osx-arm64.

Could you please provide a conda package for osx-arm64 as well?

From the pypi source it even seems as if this could be a noarch package: https://pypi.org/project/pyannote.database/#files

**Comment by tyrius02** [comment]
I'll see what I can do.

**Comment by tyrius02** [comment]
@FriederikeBrezing I have a change for pyannote.core to convert it to noarch (and 5.0.0). Once that is done I'll convert this over to noarch and 5.0.0 as well.
